### ISSUE TITLE
Class 'Meridius\PhpExcel\Workbook' not found

### ISSUE THREAD

**Issue by Daidalos117** [meridius/phpexcel#1]
Instalováno přes composer, v ExportPresenter volám  $obj = new PhpExcel\Writer(); ale writer řádek 11 hází, že nenalezl třídu Workbook. To samé když vytvořím instanci Workbooku v Presenteru ručně ... přes IDE třídu lze prokliknout. Kde je problém? :/

**Comment by meridius** [comment]
Ahoj, 
koukni prosim na testy. Je tam vzorovy reader a writer.

**Comment by Daidalos117** [comment]
Díky, toho jsem si vůbec nevšiml.
Dobrá práce!
